// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using efcoreApp.Models;

#nullable disable

namespace KuaforProjesi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241212032114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("efcoreApp.Data.Calisan", b =>
                {
                    b.Property<int>("CalisanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalisanAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CalisanSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CalisanId");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("efcoreApp.Data.CalisanIslem", b =>
                {
                    b.Property<int>("CalisanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IslemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CalisanId", "IslemId");

                    b.HasIndex("IslemId");

                    b.ToTable("CalisanIslemler");
                });

            modelBuilder.Entity("efcoreApp.Data.Islem", b =>
                {
                    b.Property<int>("IslemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IslemAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IslemId");

                    b.ToTable("Islemler");
                });

            modelBuilder.Entity("efcoreApp.Data.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MusteriId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("efcoreApp.Data.Randevu", b =>
                {
                    b.Property<int>("RandevuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalisanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IslemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MusteriId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("RandevuId");

                    b.HasIndex("CalisanId");

                    b.HasIndex("IslemId");

                    b.HasIndex("MusteriId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("efcoreApp.Data.CalisanIslem", b =>
                {
                    b.HasOne("efcoreApp.Data.Calisan", "Calisan")
                        .WithMany("CalisanIslemler")
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("efcoreApp.Data.Islem", "Islem")
                        .WithMany("CalisanIslemler")
                        .HasForeignKey("IslemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");

                    b.Navigation("Islem");
                });

            modelBuilder.Entity("efcoreApp.Data.Randevu", b =>
                {
                    b.HasOne("efcoreApp.Data.Calisan", "Calisan")
                        .WithMany()
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("efcoreApp.Data.Islem", "Islem")
                        .WithMany()
                        .HasForeignKey("IslemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("efcoreApp.Data.Musteri", "Musteri")
                        .WithMany("Randevular")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");

                    b.Navigation("Islem");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("efcoreApp.Data.Calisan", b =>
                {
                    b.Navigation("CalisanIslemler");
                });

            modelBuilder.Entity("efcoreApp.Data.Islem", b =>
                {
                    b.Navigation("CalisanIslemler");
                });

            modelBuilder.Entity("efcoreApp.Data.Musteri", b =>
                {
                    b.Navigation("Randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
