// <auto-generated />
using System;
using KuaforProjesi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KuaforProjesi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241220111309_TablolarDüzenleme")]
    partial class TablolarDüzenleme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CalisanlarimizIslem", b =>
                {
                    b.Property<int>("IslemlerIslemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("calisanlarCalisanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IslemlerIslemId", "calisanlarCalisanId");

                    b.HasIndex("calisanlarCalisanId");

                    b.ToTable("CalisanlarimizIslem");
                });

            modelBuilder.Entity("KuaforProjesi.Data.Calisanlarimiz", b =>
                {
                    b.Property<int>("CalisanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UzmanlikAlani")
                        .HasColumnType("TEXT");

                    b.Property<string>("calismaSaati")
                        .HasColumnType("TEXT");

                    b.HasKey("CalisanId");

                    b.ToTable("Calisanlarimiz");
                });

            modelBuilder.Entity("KuaforProjesi.Data.Islem", b =>
                {
                    b.Property<int>("IslemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IslemAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("fiyati")
                        .HasColumnType("INTEGER");

                    b.HasKey("IslemId");

                    b.ToTable("Islemler");
                });

            modelBuilder.Entity("KuaforProjesi.Data.Randevu", b =>
                {
                    b.Property<int>("RandevuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CalisanlarimizCalisanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IslemAdi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IslemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MusteriAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Saat")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("calisanAdi")
                        .HasColumnType("TEXT");

                    b.HasKey("RandevuId");

                    b.HasIndex("CalisanlarimizCalisanId");

                    b.HasIndex("IslemId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("KuaforProjesi.Data.Register", b =>
                {
                    b.Property<int>("RegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Eposta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .HasColumnType("TEXT");

                    b.HasKey("RegisterId");

                    b.ToTable("Registers");
                });

            modelBuilder.Entity("CalisanlarimizIslem", b =>
                {
                    b.HasOne("KuaforProjesi.Data.Islem", null)
                        .WithMany()
                        .HasForeignKey("IslemlerIslemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuaforProjesi.Data.Calisanlarimiz", null)
                        .WithMany()
                        .HasForeignKey("calisanlarCalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KuaforProjesi.Data.Randevu", b =>
                {
                    b.HasOne("KuaforProjesi.Data.Calisanlarimiz", null)
                        .WithMany("randevular")
                        .HasForeignKey("CalisanlarimizCalisanId");

                    b.HasOne("KuaforProjesi.Data.Islem", "Islem")
                        .WithMany()
                        .HasForeignKey("IslemId");

                    b.Navigation("Islem");
                });

            modelBuilder.Entity("KuaforProjesi.Data.Calisanlarimiz", b =>
                {
                    b.Navigation("randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
